---
title: "Quarto R Demo"
author: "Me"
date: today
date-format: "D MMMM YYYY"
format:
  html:
    toc: true
editor: visual
---

# Automated nested quarto tabs

We are going to create some dummy data

```{r}
#| results: asis
#| echo: false
#| warning: false

library(tidyverse)

df <- data.frame(
  org = rep_len(c('a', 'a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'b', 'b'), 12),
  kpi = rep_len(seq(1:6), 12),
  x = rnorm(12,100,25),
  y = rnorm(12,150,20)
) |>
  mutate(kpi = paste0('kpi', kpi))

# Plot Function
plot_fun <- function(data, kpi_j) {
  data |>
    filter(kpi == kpi_j) |>
    ggplot(aes(x=x, y=y)) +
    geom_point()
}

list_of_kpis <- unique(df$kpi)

```

# Next

Next we want to create a tab and chart per site and for each KPI under that site.

in principle you could use this method to create multiple layers of nested tabs

```{r}
#| results: asis
#| echo: false
#| warning: false

  cat('::: {.panel-tabset}  \n\n') 
  
  for (j in list_of_kpis) {
      cat('### Tab', j,'   \n')
      p <- plot_fun(df, j)
      print(p)
      cat('\n')
      cat('\n')
  }

cat('::: \n\n')

```

# Finish!
